# Generated by Django 5.2.1 on 2025-05-22 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_1', models.CharField(max_length=100)),
                ('nombre_2', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_estudiantil', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiadoPorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_beneficiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.dia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='FilaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficios.estudiante')),
            ],
        ),
    ]
